const matches = [
  {
    Home: "Real Madrid",
    Away: "Barcelona",
    date: "08 October",
    time: "23:00",
  },
  {
    Home: "Manchester United",
    Away: "Liverpool",
    date: "09 October",
    time: "20:30",
  },
  {
    Home: "Chelsea",
    Away: "Arsenal",
    date: "10 October",
    time: "19:00",
  },
  {
    Home: "PSG",
    Away: "Bayern Munich",
    date: "11 October",
    time: "21:45",
  },
  {
    Home: "AC Milan",
    Away: "Juventus",
    date: "12 October",
    time: "18:30",
  },
  { Home: "Real Madrid", Away: "Barcelona", date: "08 October", time: "23:00" },
  { Home: "Real Madrid", Away: "Barcelona", date: "08 October", time: "23:00" },
  { Home: "Real Madrid", Away: "Barcelona", date: "08 October", time: "23:00" },
  { Home: "Real Madrid", Away: "Barcelona", date: "08 October", time: "23:00" },
  { Home: "Real Madrid", Away: "Barcelona", date: "08 October", time: "23:00" },
];

const news = [
  {
    text: "Transfer window: Top 10 deals that shocked the football world",
    photo_url: "https://placehold.co/250x250.png",
  },
  {
    text: "World Cup 2026: New stadiums revealed for upcoming tournament",
    photo_url: "https://placehold.co/230x170.png",
  },
  {
    text: "Premier League title race heating up as season enters final stretch",
    photo_url: "https://placehold.co/230x170.png",
  },
  {
    text: "Young talent emerges as the next big star in European football",
    photo_url: "https://placehold.co/230x170.png",
  },
  {
    text: "Classic El Clasico match breaks viewership records worldwide",
    photo_url: "https://placehold.co/230x170.png",
  },
];

const players = [
  {
    id: 1,
    name: "ხვიჩა კვარაცხელია",
    jersey: 77,
    position: "Forward",
    team: "PSG",
    age: 23,
    nationality: "Georgia",
    goal: 45,
    assist: 38,
    matchPlayed: 160,
    view: 22000,
    yellowCards: 18,
    redCards: 1,
    height: 183,
    weight: 70,
    photoUrl: "./image.png",
  },
  {
    id: 2,
    name: "გიორგი მამარდაშვილი",
    jersey: 25,
    position: "Goalkeeper",
    team: "Liverpool",
    age: 24,
    nationality: "Georgia",
    goal: 0,
    assist: 0,
    matchPlayed: 120,
    view: 19000,
    yellowCards: 5,
    redCards: 0,
    height: 197,
    weight: 85,
    photoUrl: "./image.png",
  },
  {
    id: 3,
    name: "გურამ კაშია",
    jersey: 4,
    position: "Defender",
    team: "Lokomotiv Tbilisi",
    age: 37,
    nationality: "Georgia",
    goal: 20,
    assist: 10,
    matchPlayed: 500,
    view: 8000,
    yellowCards: 85,
    redCards: 6,
    height: 185,
    weight: 83,
    photoUrl: "./image.png",
  },
  {
    id: 4,
    name: "გიორგი ჩაკვეტაძე",
    jersey: 10,
    position: "Midfielder",
    team: "Gent",
    age: 25,
    nationality: "Georgia",
    goal: 30,
    assist: 25,
    matchPlayed: 140,
    view: 12000,
    yellowCards: 12,
    redCards: 1,
    height: 183,
    weight: 75,
    photoUrl: "./image.png",
  },
  {
    id: 5,
    name: "ვალერი ყაზაიშვილი",
    jersey: 8,
    position: "Midfielder",
    team: "Ulsan Hyundai",
    age: 31,
    nationality: "Georgia",
    goal: 95,
    assist: 60,
    matchPlayed: 400,
    view: 10000,
    yellowCards: 28,
    redCards: 2,
    height: 176,
    weight: 73,
    photoUrl: "./image.png",
  },
  {
    id: 6,
    name: "ბუდუ ზივზივაძე",
    jersey: 9,
    position: "Forward",
    team: "Karlsruhe",
    age: 30,
    nationality: "Georgia",
    goal: 110,
    assist: 35,
    matchPlayed: 320,
    view: 9500,
    yellowCards: 20,
    redCards: 1,
    height: 185,
    weight: 80,
    photoUrl: "./image.png",
  },
  {
    id: 7,
    name: "ლაშა დვალი",
    jersey: 5,
    position: "Defender",
    team: "APOEL Nicosia",
    age: 29,
    nationality: "Georgia",
    goal: 15,
    assist: 8,
    matchPlayed: 270,
    view: 8700,
    yellowCards: 40,
    redCards: 3,
    height: 191,
    weight: 85,
    photoUrl: "./image.png",
  },
  {
    id: 8,
    name: "სანდრო ალთუნაშვილი",
    jersey: 6,
    position: "Midfielder",
    team: "Maccabi Netanya",
    age: 26,
    nationality: "Georgia",
    goal: 20,
    assist: 18,
    matchPlayed: 200,
    view: 7200,
    yellowCards: 25,
    redCards: 1,
    height: 178,
    weight: 72,
    photoUrl: "./image.png",
  },
  {
    id: 9,
    name: "ჯაბა კანკავა",
    jersey: 7,
    position: "Midfielder",
    team: "Slovan Bratislava",
    age: 38,
    nationality: "Georgia",
    goal: 25,
    assist: 22,
    matchPlayed: 520,
    view: 6500,
    yellowCards: 95,
    redCards: 7,
    height: 177,
    weight: 74,
    photoUrl: "./image.png",
  },
  {
    id: 10,
    name: "დავითაშვილი ზურიკო",
    jersey: 7,
    position: "Midfielder",
    team: "Bordeaux",
    age: 23,
    nationality: "Georgia",
    goal: 22,
    assist: 27,
    matchPlayed: 150,
    view: 11500,
    yellowCards: 18,
    redCards: 1,
    height: 180,
    weight: 73,
    photoUrl: "./image.png",
  },
  {
    id: 11,
    name: "გიორგი ქვილითაია",
    jersey: 9,
    position: "Forward",
    team: "APOEL Nicosia",
    age: 30,
    nationality: "Georgia",
    goal: 100,
    assist: 40,
    matchPlayed: 310,
    view: 8700,
    yellowCards: 30,
    redCards: 2,
    height: 186,
    weight: 81,
    photoUrl: "./image.png",
  },
  {
    id: 12,
    name: "ოთარ კიტეიშვილი",
    jersey: 8,
    position: "Midfielder",
    team: "Sturm Graz",
    age: 28,
    nationality: "Georgia",
    goal: 40,
    assist: 35,
    matchPlayed: 260,
    view: 9600,
    yellowCards: 22,
    redCards: 2,
    height: 178,
    weight: 72,
    photoUrl: "./image.png",
  },
  {
    id: 13,
    name: "ლუკა ლოჩოშვილი",
    jersey: 5,
    position: "Defender",
    team: "Cremonese",
    age: 25,
    nationality: "Georgia",
    goal: 7,
    assist: 5,
    matchPlayed: 130,
    view: 7200,
    yellowCards: 28,
    redCards: 2,
    height: 192,
    weight: 84,
    photoUrl: "./image.png",
  },
  {
    id: 14,
    name: "გიორგი მიქაუტაძე",
    jersey: 10,
    position: "Forward",
    team: "Metz",
    age: 24,
    nationality: "Georgia",
    goal: 75,
    assist: 25,
    matchPlayed: 190,
    view: 15000,
    yellowCards: 15,
    redCards: 1,
    height: 181,
    weight: 74,
    photoUrl: "./image.png",
  },
  {
    id: 15,
    name: "ნიკა კვეკვესკირი",
    jersey: 6,
    position: "Midfielder",
    team: "Lech Poznań",
    age: 32,
    nationality: "Georgia",
    goal: 18,
    assist: 22,
    matchPlayed: 310,
    view: 7400,
    yellowCards: 35,
    redCards: 2,
    height: 185,
    weight: 77,
    photoUrl: "./image.png",
  },
];

const tournaments = [
  {
    id: 1,
    name: "gff",
    age: "u-19",
    teams: [
      {
        team: "იბერია 1999",
        played: 16,
        won: 13,
        drawn: 2,
        lost: 1,
        for: 41,
        against: 14,
        goalDifference: 27,
        points: 41,
      },
      {
        team: "დინამო თბილისი",
        played: 16,
        won: 12,
        drawn: 2,
        lost: 2,
        for: 47,
        against: 19,
        goalDifference: 28,
        points: 38,
      },
      {
        team: "ტორპედო",
        played: 16,
        won: 9,
        drawn: 2,
        lost: 5,
        for: 26,
        against: 18,
        goalDifference: 8,
        points: 29,
      },
      {
        team: "ლოკომოტივი",
        played: 16,
        won: 8,
        drawn: 2,
        lost: 6,
        for: 31,
        against: 23,
        goalDifference: 8,
        points: 26,
      },
      {
        team: "დინამო ბათუმი",
        played: 16,
        won: 8,
        drawn: 1,
        lost: 7,
        for: 35,
        against: 35,
        goalDifference: 0,
        points: 25,
      },
      {
        team: "კოლხეთი 1913",
        played: 16,
        won: 7,
        drawn: 2,
        lost: 7,
        for: 25,
        against: 28,
        goalDifference: -3,
        points: 23,
      },
      {
        team: "ვიტი-ჯორჯია",
        played: 16,
        won: 5,
        drawn: 0,
        lost: 11,
        for: 26,
        against: 45,
        goalDifference: -19,
        points: 15,
      },
      {
        team: "დილა",
        played: 16,
        won: 4,
        drawn: 1,
        lost: 11,
        for: 20,
        against: 43,
        goalDifference: -23,
        points: 13,
      },
      {
        team: "თელავი",
        played: 16,
        won: 3,
        drawn: 4,
        lost: 9,
        for: 17,
        against: 28,
        goalDifference: -11,
        points: 13,
      },
      {
        team: "საბურთალო",
        played: 16,
        won: 3,
        drawn: 0,
        lost: 13,
        for: 25,
        against: 40,
        goalDifference: -15,
        points: 9,
      },
    ],
  },
  {
    id: 2,
    age: "u-17",
    name: "league",
    teams: [
      {
        team: "Inter",
        played: 6,
        won: 6,
        drawn: 0,
        lost: 0,
        for: 19,
        against: 7,
        goalDifference: 12,
        points: 18,
      },
      {
        team: "Sporting CP",
        played: 6,
        won: 5,
        drawn: 1,
        lost: 0,
        for: 13,
        against: 3,
        goalDifference: 10,
        points: 16,
      },
      {
        team: "Salzburg",
        played: 6,
        won: 5,
        drawn: 1,
        lost: 0,
        for: 17,
        against: 9,
        goalDifference: 8,
        points: 16,
      },
      {
        team: "Barcelona",
        played: 6,
        won: 5,
        drawn: 0,
        lost: 1,
        for: 17,
        against: 10,
        goalDifference: 7,
        points: 15,
      },
      {
        team: "Milan",
        played: 6,
        won: 4,
        drawn: 1,
        lost: 1,
        for: 14,
        against: 8,
        goalDifference: 6,
        points: 13,
      },
      {
        team: "Juventus",
        played: 6,
        won: 3,
        drawn: 1,
        lost: 2,
        for: 12,
        against: 11,
        goalDifference: 1,
        points: 10,
      },
      {
        team: "Roma",
        played: 6,
        won: 2,
        drawn: 1,
        lost: 3,
        for: 9,
        against: 12,
        goalDifference: -3,
        points: 7,
      },
      {
        team: "Napoli",
        played: 6,
        won: 1,
        drawn: 1,
        lost: 4,
        for: 7,
        against: 15,
        goalDifference: -8,
        points: 4,
      },
      {
        team: "Benfica",
        played: 6,
        won: 4,
        drawn: 1,
        lost: 1,
        for: 13,
        against: 7,
        goalDifference: 6,
        points: 13,
      },
      {
        team: "PSG",
        played: 6,
        won: 4,
        drawn: 0,
        lost: 2,
        for: 15,
        against: 9,
        goalDifference: 6,
        points: 12,
      },
      {
        team: "Arsenal",
        played: 6,
        won: 3,
        drawn: 2,
        lost: 1,
        for: 11,
        against: 6,
        goalDifference: 5,
        points: 11,
      },
      {
        team: "Real Madrid",
        played: 6,
        won: 3,
        drawn: 1,
        lost: 2,
        for: 12,
        against: 9,
        goalDifference: 3,
        points: 10,
      },
      {
        team: "Bayern",
        played: 6,
        won: 3,
        drawn: 1,
        lost: 2,
        for: 13,
        against: 12,
        goalDifference: 1,
        points: 10,
      },
      {
        team: "Atletico",
        played: 6,
        won: 2,
        drawn: 2,
        lost: 2,
        for: 10,
        against: 10,
        goalDifference: 0,
        points: 8,
      },
      {
        team: "Porto",
        played: 6,
        won: 2,
        drawn: 2,
        lost: 2,
        for: 9,
        against: 11,
        goalDifference: -2,
        points: 8,
      },
      {
        team: "RB Leipzig",
        played: 6,
        won: 2,
        drawn: 1,
        lost: 3,
        for: 10,
        against: 12,
        goalDifference: -2,
        points: 7,
      },
      {
        team: "Dortmund",
        played: 6,
        won: 2,
        drawn: 1,
        lost: 3,
        for: 9,
        against: 12,
        goalDifference: -3,
        points: 7,
      },
      {
        team: "Ajax",
        played: 6,
        won: 1,
        drawn: 2,
        lost: 3,
        for: 8,
        against: 12,
        goalDifference: -4,
        points: 5,
      },
      {
        team: "Celtic",
        played: 6,
        won: 1,
        drawn: 1,
        lost: 4,
        for: 6,
        against: 14,
        goalDifference: -8,
        points: 4,
      },
    ],
  },
  {
    id: 3,
    name: "imereti",
    age: "u-19",
    teams: [
      {
        team: "ივერია ხაშური",
        played: 12,
        won: 11,
        drawn: 0,
        lost: 1,
        for: 35,
        against: 11,
        goalDifference: 24,
        points: 33,
      },
      {
        team: "დინამო 1 ბათუმი",
        played: 12,
        won: 10,
        drawn: 1,
        lost: 1,
        for: 46,
        against: 14,
        goalDifference: 32,
        points: 31,
      },
      {
        team: "მარნეთი ქუთაისი",
        played: 12,
        won: 7,
        drawn: 2,
        lost: 3,
        for: 32,
        against: 19,
        goalDifference: 13,
        points: 23,
      },
      {
        team: "მარგვეთი 2006 ზესტაფონი",
        played: 12,
        won: 7,
        drawn: 0,
        lost: 5,
        for: 31,
        against: 25,
        goalDifference: 6,
        points: 21,
      },
      {
        team: "ბაია ზუგდიდი",
        played: 12,
        won: 6,
        drawn: 0,
        lost: 6,
        for: 18,
        against: 21,
        goalDifference: -3,
        points: 18,
      },
      {
        team: "ჩელე აკადემია 1 ქობულეთი",
        played: 12,
        won: 5,
        drawn: 2,
        lost: 5,
        for: 16,
        against: 12,
        goalDifference: 4,
        points: 17,
      },
      {
        team: "სასს სტარტი",
        played: 12,
        won: 5,
        drawn: 0,
        lost: 7,
        for: 26,
        against: 31,
        goalDifference: -5,
        points: 15,
      },
      {
        team: "რაკეტა ამბროლაური",
        played: 12,
        won: 2,
        drawn: 1,
        lost: 9,
        for: 6,
        against: 22,
        goalDifference: -16,
        points: 7,
      },
      {
        team: "ბახმარო ჩოხატაური",
        played: 12,
        won: 2,
        drawn: 1,
        lost: 9,
        for: 11,
        against: 37,
        goalDifference: -26,
        points: 7,
      },
      {
        team: "სევანელი ქუთაისი",
        played: 12,
        won: 1,
        drawn: 1,
        lost: 10,
        for: 12,
        against: 41,
        goalDifference: -29,
        points: 4,
      },
    ],
  },
];

export { matches, news, players, tournaments };
